import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — ChatKit",
  description: "Terms and conditions for using ChatKit.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
      <h1 className="text-3xl font-bold">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Last updated: May 2026
      </p>

      <div className="mt-8 space-y-8 text-sm leading-relaxed text-muted-foreground">
        <section>
          <h2 className="text-lg font-semibold text-foreground">1. Acceptance of Terms</h2>
          <p className="mt-2">
            By accessing and using ChatKit (&quot;the Service&quot;), you accept and agree to be
            bound by these Terms of Service. If you do not agree, please do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">2. Description of Service</h2>
          <p className="mt-2">
            ChatKit is an AI-powered chat application that provides conversational AI
            responses. The Service includes:
          </p>
          <ul className="mt-1 list-disc space-y-1 pl-5">
            <li>AI chat with multiple model options.</li>
            <li>Conversation history and management.</li>
            <li>Usage tracking and plan management.</li>
            <li>Admin dashboard for service administrators.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">3. User Accounts</h2>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>You must provide a valid email address to create an account.</li>
            <li>You are responsible for maintaining the security of your account credentials.</li>
            <li>You may not share your account with others.</li>
            <li>You must be at least 13 years old to use this Service.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">4. Acceptable Use</h2>
          <p className="mt-2">You agree NOT to:</p>
          <ul className="mt-1 list-disc space-y-1 pl-5">
            <li>Use the Service for illegal activities or to generate illegal content.</li>
            <li>Attempt to bypass rate limits, security measures, or access controls.</li>
            <li>Generate malware, exploits, phishing content, or harmful code.</li>
            <li>Impersonate others or provide false information.</li>
            <li>Use the Service to harass, threaten, or harm others.</li>
            <li>Reverse engineer, decompile, or attempt to extract the Service&apos;s source code.</li>
            <li>Use automated tools to access the Service without authorization.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">5. Plans &amp; Billing</h2>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Free plans have daily message limits as specified in the pricing page.</li>
            <li>Paid plans are billed according to the terms selected at purchase.</li>
            <li>We reserve the right to change pricing with 30 days&apos; notice.</li>
            <li>Usage limits may vary by plan and are subject to fair use policies.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">6. AI-Generated Content</h2>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>AI responses are generated by machine learning models and may be inaccurate.</li>
            <li>You are responsible for verifying the accuracy of AI-generated content.</li>
            <li>We do not guarantee the correctness, completeness, or usefulness of AI responses.</li>
            <li>AI responses should not be used as professional advice (medical, legal, financial, etc.).</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">7. Intellectual Property</h2>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>You retain ownership of the content you input into the Service.</li>
            <li>AI-generated responses may be used by you as permitted by applicable law.</li>
            <li>The ChatKit name, logo, and interface design are the property of ChatKit.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">8. Privacy</h2>
          <p className="mt-2">
            Your privacy is important to us. Our data practices are described in our{" "}
            <a href="/privacy" className="text-primary hover:underline">
              Privacy Policy
            </a>
            , which is incorporated into these Terms by reference.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">9. Termination</h2>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>You may delete your account at any time from the Settings page.</li>
            <li>We may suspend or terminate accounts that violate these Terms.</li>
            <li>Upon termination, your data will be deleted within 30 days.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">10. Disclaimer of Warranties</h2>
          <p className="mt-2">
            The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any
            kind, either express or implied. We do not guarantee uninterrupted or error-free
            operation of the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">11. Limitation of Liability</h2>
          <p className="mt-2">
            To the maximum extent permitted by law, ChatKit shall not be liable for any
            indirect, incidental, special, consequential, or punitive damages arising out of
            or related to your use of the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">12. Changes to Terms</h2>
          <p className="mt-2">
            We may update these Terms from time to time. We will notify users of material
            changes via email or a notice on the Service. Continued use after changes
            constitutes acceptance of the updated Terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">13. Contact</h2>
          <p className="mt-2">
            For questions about these Terms, please contact us at the email address
            provided during purchase.
          </p>
        </section>
      </div>

      <div className="mt-12 border-t border-border pt-6 text-center">
        <a href="/privacy" className="text-sm text-primary hover:underline">
          ← Privacy Policy
        </a>
      </div>
    </div>
  );
}
